### ISSUE TITLE
Missing step : include("CMake_nRF5x.cmake")  from CMakeLists.txt ?

### ISSUE THREAD

**Issue by bootchk** [Polidea/cmake-nRF5x#1]
Is this step missing from the tutorial in the readme?

Without it, I get: 

CMake Error at CMakeLists.txt:13 (nRF5x_setup):
  Unknown CMake command "nRF5x_setup".

when I run:  cmake -H. -B"cmake-build" -G "Unix Makefiles"

although I think I followed your tutorial closely.

Alternatively, can you link to a project that uses your cmake script?  Or put a template CMakeLists.txt in your repository?  That might help other CMake newbies like myself.

**Comment by dariuszseweryn** [comment]
Hello @bootchk 
That is true. The readme was missing this statement. I have just fixed it.

Unfortunately there is no publicly available project that I could link to. The template does not make sense since the Readme is updated.

I am trying to use this script so I might have some time for improvements—yet I am also a newbie
