### ISSUE TITLE
Incompatible with newer NRF SDK 14.2

### ISSUE THREAD

**Issue by bootchk** [Polidea/cmake-nRF5x#2]
It seems that Nordic restructured SDK directories and renamed some files, e.g. softdevice_handler.c is now called sdh.c ?  And location of RTT files changed?

I don't expect anyone to fix this, just noting that users of the script might need to adjust for SDK versions other than 12.3 used by the script.

**Comment by dariuszseweryn** [comment]
PRs are welcome though :) I will try to look after this project since the original author has other responsibilities now.

**Comment by bootchk** [comment]
I used your scripts in another repository, it contains a script with additions for SDK v14.2  https://github.com/bootchk/libBLEProvisionee/blob/master/CMakeScripts/CMake_nRF5x_v14_2.cmake
I am not sure it is complete.  I think you should split out all the SDK version dependent cmake commands into a separate file.  A perpetual problem:  keeping current with Nordic SDK versions.

**Comment by dariuszseweryn** [comment]
Hello,

Sorry for such a tremendous delay. I did not have time to look into this repository. Recently we have got a contribution that aligns this repo with SDK 15.3.0.

I see that you have moved from using this script and the file you mentioned did not seem to be complete as of [this commit](https://github.com/bootchk/libBLEProvisionee/blob/67dd75a03b2d81e4632040084938da3bb3cb944e/CMakeScripts/CMake_nRF5x_v14_2.cmake).

In this situation I do not see a point to integrate it since SDK 15 is ready to use and more complete.

Best regards
